spring:
  application:
    name: scw-ui
  redis:
    host: 47.103.83.98
    port: 6399
  session:
    timeout:
      seconds: 1800
    store-type: redis

server:
  port: 10000
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 47.103.83.98
  client:
    service-url:
      defaultZone: http://106.15.226.67:8761/eureka/
#feign:
#  hystrix:
#    enabled: true
