spring:
  application:
    name: scw-ui
  redis:
    host: 192.168.175.66
    port: 6399
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  session:
    timeout:
      seconds: 1800
    store-type: redis

server:
  port: 10000
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
